version: '3.8'

services:
  backend:
    container_name: bridge-api
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start
    volumes:
      - ./backend/api/:/app
    ports:
      - 8000:8000
    env_file:
      - ./backend/api/.env
    depends_on:
      - redis
      - db

  frontend:
    container_name: react-frontend
    build:
      context: .
      dockerfile: ./compose/react/Dockerfile
    command: /start-react
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  reverse_proxy:
    build: ./compose/nginx
    ports:
      - 81:80
    depends_on:
      - backend
      - frontend

  worker:
    restart: unless-stopped
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    command: /start-celeryworker
    volumes:
      - ./backend/api/:/app
    env_file: ./backend/api/.env
    depends_on:
      - db
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  db:
    image: postgres:15
    container_name: bridge-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file: ./backend/api/.env
    environment:
      SQL_HOST: db
    ports:
      - 5432:5432
    expose:
      - "5432"

volumes:
  postgres_data:
