version: '3.8'

services:
  bridge-api:
    build: ./backend/api
    container_name: bridge-api
    volumes:
      - ./backend/api/:/api
    ports:
      - 8000:8000
    env_file:
      - ./backend/api/.env

  db:
    image: postgres:15
    container_name: bridge-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bridge_app

volumes:
  postgres_data:
