version: '3.8'

services:
  backend:
    build: ./backend/api
    container_name: bridge-api
    volumes:
      - ./backend/api/:/api
    ports:
      - 8000:8000
    env_file:
      - ./backend/api/.env

  frontend:
    container_name: react-frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - './frontend:/frontend'
      - '/frontend/node_modules'
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true

  reverse_proxy:
    build: ./nginx
    ports:
      - 81:80
    depends_on:
      - backend
      - frontend

  worker:
    restart: unless-stopped
    build: ./backend/api
    volumes:
      - ./backend/api/:/api
    depends_on:
      - backend
      - redis

  redis:
    image: redis:7-alpine
    ports:
      - 6379:6379

  db:
    image: postgres:15
    container_name: bridge-db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=bridge_app

volumes:
  postgres_data:
