# Generated by Django 4.2.7 on 2023-12-06 14:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="directories",
            field=models.JSONField(default=["Other"]),
        ),
    ]
