# Generated by Django 4.2.7 on 2023-12-06 14:58

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_profile_directories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="directories",
            field=models.JSONField(default=users.models.default_directories),
        ),
    ]
