# Generated by Django 4.2.7 on 2023-11-14 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="deal",
            name="info",
        ),
        migrations.AddField(
            model_name="deal",
            name="deal_info",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="deal",
            name="name",
            field=models.CharField(default="name", max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="deal",
            name="result_table",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="deal",
            name="tournament",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="deals.tournament",
            ),
        ),
    ]
