# Generated by Django 4.2.7 on 2023-11-19 18:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="deal",
            name="visiblity",
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
