# Generated by Django 4.2.7 on 2023-11-20 02:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0004_alter_deal_deal_info_alter_deal_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="tag",
            new_name="tags",
        ),
    ]
