# Generated by Django 4.2.7 on 2023-12-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0005_rename_tag_comment_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(related_name="tags", to="deals.tag"),
        ),
        migrations.AlterField(
            model_name="tournament",
            name="series",
            field=models.CharField(max_length=100),
        ),
    ]
