# Generated by Django 4.2.7 on 2023-12-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0008_alter_comment_body_alter_comment_difficulty_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tags", to="deals.tag"
            ),
        ),
    ]
