# Generated by Django 5.0 on 2023-12-12 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0010_alter_deal_author"),
        ("users", "0005_profile_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="users.profile",
            ),
        ),
    ]
