# Generated by Django 5.0 on 2023-12-12 23:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0011_alter_comment_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="comments", to="deals.tag"
            ),
        ),
    ]
