# Generated by Django 5.0 on 2024-01-09 19:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0012_alter_comment_tags"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="comment",
            name="visibility",
        ),
        migrations.RemoveField(
            model_name="deal",
            name="visibility",
        ),
        migrations.AddField(
            model_name="comment",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="difficulty",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(5)],
            ),
        ),
    ]
