# Generated by Django 5.0 on 2024-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("deals", "0013_remove_comment_visibility_remove_deal_visibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="directory",
            field=models.CharField(default="Other", max_length=100),
        ),
    ]
